### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by c4n1** [Owlz/winevt#1]
I had a look at this as it seemed useful for something I'm writing at the moment but couldn't get it to import.

Install from pip
```
pip install winevt
Collecting winevt
  Downloading winevt-0.0.9.tar.gz
Collecting cffi>=1.0.0 (from winevt)
  Downloading cffi-1.10.0-cp36-cp36m-win32.whl (149kB)
    100% |████████████████████████████████| 153kB 2.5MB/s
Collecting untangle (from winevt)
  Downloading untangle-1.1.1.tar.gz
Collecting pycparser (from cffi>=1.0.0->winevt)
  Downloading pycparser-2.17.tar.gz (231kB)
    100% |████████████████████████████████| 235kB 2.2MB/s
Installing collected packages: pycparser, cffi, untangle, winevt
  Running setup.py install for pycparser ... done
  Running setup.py install for untangle ... done
  Running setup.py install for winevt ... done
```

import with IDLE
```
>>> from winevt import EventLog
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python-VENV\Server-Checkups\lib\site-packages\winevt\__init__.py", line 17, in <module>
    from ._winevt import ffi, lib as evtapi
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

**Comment by bannsec** [comment]
Oh interesting. Looks like you're using the 32-bit version.  Hadn't tested that. Looks like i wasn't catching that exception, try again now:

```bash
pip install git+https://github.com/Owlz/winevt.git
```

**Comment by c4n1** [comment]
Just tested and it's working thanks

**Comment by bannsec** [comment]
Awesome. Thanks!
